// <auto-generated />
namespace MavroTag.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Texts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Texts));
        
        string IMigrationMetadata.Id
        {
            get { return "202207021954250_Texts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
